from django.db import models

class Job(models.Model):
    createUser = models.CharField(max_length=50)
    change_password = models.CharField(max_length=50)
    Image = models.ImageField(upload_to="data")
    Email = models.EmailField(rel="mail")
    IPAddress = models.IntegerField()
    token = models.TextField()
    refreshExpiresIn = models.CharField(max_length=60)
    exp = models.CharField(max_length=60)
    origIat = models.CharField(max_length=60)
    username = models.CharField(max_length=60)
    Email_an_image = models.ImageField(upload_to="data")
    BASE_DIR = models.CharField(max_length=60)
    SECRET_KEY = models.TextField()
    DEBUG = models.CharField(max_length=60)
    ALLOWED_HOSTS = models.CharField(max_length=60)
    INSTALLED_APPS = models.TextField()
    GRAPHENE = models.TextField()
    MIDDLEWARE = models.TextField()
    CORS_ORIGIN_ALLOW_ALL = models.CharField(max_length=60)
    AUTHENTICATION_BACKENDS = models.TextField()
    ROOT_URLCONF = models.CharField(max_length=60)
    TEMPLATES = models.TextField()
    WSGI_APPLICATION = models.CharField(max_length=60)
    DATABASES = models.TextField()
    AUTH_PASSWORD_VALIDATORS = models.TextField()
    LANGUAGE_CODE = models.CharField(max_length=60)
    TIME_ZONE = models.CharField(max_length=60)
    USE_I18N = models.CharField(max_length=60)
    USE_L10N = models.CharField(max_length=60)
    USE_TZ = models.CharField(max_length=60)
    STATIC_URL = models.CharField(max_length=60)
    MEDIA_ROOT = models.CharField(max_length=60)
    MEDIA_URL = models.CharField(max_length=60)
