input(print("'PORT': '',"))
input(print("'HOST': 'localhost',"))
input(print("'PASSWORD': '12345',"))
input(print("'USER': 'mynonsuperuser',"))
input(print("'NAME': 'db',"))
input()
input()
input()
input()
input()
input()
input()
input()
input()
input()
input()
input()
input()
input()
breakpoint()
